### ISSUE TITLE
Displaying "#" is not possible

### ISSUE THREAD

**Issue by c0zmo** [hbekel/overlay64#1]
The config phrase <write 5 7 "#1"> will not work. I guess it is because "#" is the comment character. "\#" doesn't work either.

In the beta-version of October 2016, this worked. Could you "escape" the #-character? :)

**Comment by hbekel** [comment]
Yes, it's a bug, I'll have to rethink parsing a bit for this.

For now, please fix it in the binary config (sorry). You should be able to locate the strings easily. Just add a "?" or similar and replace it with a hex editor.

**Comment by hbekel** [comment]
This was easier than I thought, fixed in [this commit](https://github.com/hbekel/overlay64/commit/fe3f13489bd16b36742bf3b185f16c05530a3879).

Thanks for reporting this issue :)

**Comment by c0zmo** [comment]
It's a little buggy... sorry...
In my config, I made a "input line test mode"... It basically displays the state of all 24 control lines. With the new update, every other line containing "#" is NOT displayed properly... Please, check my config:

```
screen

write 4 3 " "
write 5 7 "*** OVERLAY64 INPUT LINE TEST MODE ***"
write 6 3 " "
write 8 7 "#00  #01  #02  #03  #04  #05  #06  #07"
write 12 7 "#08  #09  #10  #11  #12  #13  #14  #15"
write 16 7 "#16  #17  #18  #19  #20  #21  #22  #23"

sample 0
    when 0 write 9 6 " LOW"
    when 1 write 9 6 "HIGH"

sample 1
    when 0 write 9 11 " LOW"
    when 1 write 9 11 "HIGH"

[cont'd]
```
The first and third rows are displayed. The second row (write 12 7) is not displayed.
If I now put a new line in there, i. e. "write 11 7 'THIS IS #1'", then that text is displayed as "THIS IS", the 2nd row is shown, but the 3rd isn't. I hope I could make that clear ;)

**Comment by hbekel** [comment]
Properly fixed in this [commit](https://github.com/hbekel/overlay64/commit/7e69f4f1469c4188bf8d5f199b9f4ac93d80f1e6)
