### ISSUE TITLE
Device resets into Bootloader after config is sent

### ISSUE THREAD

**Issue by c0zmo** [hbekel/overlay64#2]
I compiled software and firmware from todays sources (30 Jan 17). Now, with "overlay64 configure config.txt" the config is translated and sent to the device, but then it shows "Resetting device......" for 6-8 seconds. After that, the Overlay64 is in boot loader mode.
I'm using Prototype V2 Hardware, if that matters...

**Comment by hbekel** [comment]
Please make sure you are actually using both the new firmware and the new software. At the terminal, run 

    $ which overlay64

The device should not be in bootloader mode, since flashing the configuration does no longer involve the bootloader at all. The only reason I can think of is that you are still using the old client, which sends the command to enter the bootloader and then flashes via the usbasp interface.

**Comment by c0zmo** [comment]
Firmware and software are from the current branch. I just re-installed the firmware, and there the reset works:

```
markus@LE752:~/overlay64-master-20170130/firmware$ overlay64 update main.hex 
Trying to parse Intel HEX format...OK
Parsed 17152 bytes starting at 0x00
Entering bootloader..
USBaspLoader (C)2008 by OBJECTIVE DEVELOPMENT Software GmbH
Updating application: 17152 of 17152 bytes transferred...OK
Resetting device...
overlay64 firmware 1.0 Jan 30 2017 18:50:01
```

But when flashing the config, the device stays in Bootloader-mode:

```
markus@LE752:~/overlay-config$ overlay64 configure o64-c0z.conf 
Reading o64-c0z.conf...
SRAM:	 3249 of 16384 bytes used (13135 bytes free)
EEPROM:	  866 of  4096 bytes used ( 3230 bytes free)
Flashing configuration: 866 bytes...ok
Resetting device..........markus@LE752:~/overlay-config$ overlay64 identify
USBaspLoader (C)2008 by OBJECTIVE DEVELOPMENT Software GmbH
```
Using the reset-command works though.

**Comment by c0zmo** [comment]
Just an update, even with the latest firmware this issue is still there. Maybe you can take a look at it this weekend. ;-)

**Comment by hbekel** [comment]
I could not reproduce this issue and I haven't had anyone else reporting this, so I assume the issue is somewhere on your system. We can look into it tomorrow :)

**Comment by c0zmo** [comment]
As it turned out, the problem seems to have been my self-compiled firmware. After we flashed the stock bootloader and firmware image with your computer on DoReCo, the problem disappeared.

Sorry for any inconvenience.
c0z
