### ISSUE TITLE
Characters "=" is not usable in write-command

### ISSUE THREAD

**Issue by c0zmo** [hbekel/overlay64#3]
Using the character "=" is not possible with the write-command. The parser gives me an error:
"Speicherzugriffsfehler (Speicherabzug geschrieben)"

**Comment by hbekel** [comment]
I'll look into this, thanks.

If you report errors, please issue "export LANG=c" before issuing the command. This way system error messages will be in English :)

**Comment by hbekel** [comment]
Fixed in commit 49accf9f360fa6744038ed0f16755a0f68a925db
